version: 1
accounts:
- name: alice
  coins:
  - 200000000000token
  - 200000000stake
  mnemonic: buddy alpha peasant tobacco segment ice tired floor forward fresh chef
    vital plunge subway include lava skate bulk during garlic sea nothing garage tribe
- name: bob
  coins:
  - 100000000000token
  - 100000000stake
  mnemonic: still orbit more fruit smoke describe cute harvest scrub boring fit oven
    visual fun stereo burger parent cheap require valid cloud pudding pair equip
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    did:
      orgsCount: 1
  chain_id: did_0708
validators:
- name: alice
  bonded: 100000000stake
